# 构建阶段
FROM node:20-alpine AS builder

WORKDIR /app

# 复制 package.json 和 package-lock.json 和 yarn.lock
COPY package*.json ./
COPY yarn.lock ./

# 安装依赖
RUN npx yarn

# 复制源代码
COPY . .

# 构建应用
RUN npm run build


########################################################


# 生产阶段
FROM node:20-alpine AS runner

WORKDIR /app

# 设置环境变量
ENV NODE_ENV=production

# 复制必要文件
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/yarn.lock ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./

# 仅安装生产依赖
RUN npx yarn --only=production

# 暴露端口
EXPOSE 3000

# 启动应用
CMD ["npm", "start"]