source 'https://gems.ruby-china.com/'

cocoapods_version = '1.12.1'

gem 'activesupport', '6.1.4.1'

gem 'cocoapods', cocoapods_version
ENV['CP_CACHE_DIR'] = File.join(Dir.home, 'Library/Caches/CocoaPods', cocoapods_version)

gem 'xcodeproj', '1.27.0'