name: Arkitect CI
on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          sudo -H apt update -y
          sudo -H apt install -y sudo
          sudo apt install -y git curl
          curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install conventional-changelog-atom
          npm install @commitlint/config-conventional
          npm install @commitlint/format
          npm install commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  Run-All-CI:
    permissions:
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install and configure Uv
        run: |
          make uv_install
      - name: Install requirements
        run: make install_ci
      - name: Lint
        run: make lint
      - name: Test
        run: make test
